name: transformerv2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2021.10.8=ha878542_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.2.1=cuda11.3_0
  - ffmpeg=4.3.2=hca11adc_0
  - freetype=2.10.4=h0708190_1
  - gettext=0.19.8.1=h0b5b191_1005
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - lame=3.100=h7f98852_1001
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libblas=3.9.0=11_linux64_openblas
  - libcblas=3.9.0=11_linux64_openblas
  - libffi=3.3=he6710b0_2
  - libflac=1.3.3=h9c3ff4c_1
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libgomp=9.3.0=h5101ec6_17
  - liblapack=3.9.0=11_linux64_openblas
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libsndfile=1.0.31=h9c3ff4c_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libvorbis=1.3.7=h9c3ff4c_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.4=py38h06a4308_0
  - pysoundfile=0.10.3.post1=pyhd3deb0d_0
  - python=3.8.12=h12debd9_0
  - python_abi=3.8=2_cp38
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py38h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - x264=1!161.3030=h7f98852_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.15.0
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - argon2-cffi==21.1.0
    - astunparse==1.6.3
    - attrs==21.2.0
    - audioread==3.0.0
    - backcall==0.2.0
    - bleach==4.1.0
    - cachetools==4.2.4
    - certifi==2020.4.5.1
    - cffi==1.14.0
    - chainer==7.8.1
    - charset-normalizer==2.0.7
    - ci-sdr==0.0.0
    - clang==5.0
    - click==8.1.2
    - configargparse==1.5.3
    - ctc-segmentation==1.7.1
    - cycler==0.10.0
    - cython==0.29.28
    - debugpy==1.5.1
    - decorator==4.4.2
    - defusedxml==0.7.1
    - dill==0.3.1.1
    - distance==0.1.3
    - editdistance==0.6.0
    - einops==0.4.1
    - entrypoints==0.3
    - espnet==202301
    - espnet-tts-frontend==0.0.3
    - fast-bss-eval==0.1.3
    - fastdtw==0.3.4
    - filelock==3.6.0
    - flatbuffers==1.12
    - future==0.18.2
    - g2p-en==2.1.0
    - gast==0.4.0
    - glob2==0.7
    - google-auth==2.3.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.41.1
    - h5py==3.1.0
    - humanfriendly==10.0
    - hydra-core==1.3.1
    - idna==3.3
    - importlib-metadata==4.13.0
    - importlib-resources==5.10.2
    - inflect==5.3.0
    - ipykernel==6.4.2
    - ipython==7.28.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jaconv==0.3
    - jamo==0.4.1
    - jedi==0.18.0
    - jinja2==3.0.2
    - joblib==0.14.1
    - jsonpatch==1.32
    - jsonpointer==2.1
    - jsonschema==4.1.2
    - jupyter==1.0.0
    - jupyter-client==7.0.6
    - jupyter-console==6.4.0
    - jupyter-core==4.9.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.2
    - kaldiio==2.17.2
    - keras==2.6.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.2.0
    - librosa==0.9.2
    - llvmlite==0.32.0
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.2.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - multiprocess==0.70.9
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - nltk==3.7
    - notebook==6.4.5
    - numba==0.49.0
    - numpy==1.18.4
    - oauthlib==3.1.1
    - omegaconf==2.3.0
    - opt-einsum==3.3.0
    - packaging==21.2
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.1.2
    - pooch==1.5.2
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.21
    - protobuf==3.11.3
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.10.0
    - pykaldi==0.0.1
    - pymcd==0.2.1
    - pynndescent==0.5.5
    - pyparsing==2.4.7
    - pypinyin==0.44.0
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.0
    - pyrsistent==0.18.0
    - pysptk==0.2.0
    - python-dateutil==2.8.1
    - python-graphviz==0.18.2
    - pytorch-ranger==0.1.1
    - pytorch-wpe==0.0.1
    - pytz==2021.3
    - pyworld==0.3.0
    - pyyaml==5.3.1
    - pyzmq==22.3.0
    - qtconsole==5.1.1
    - qtpy==1.11.2
    - regex==2022.3.15
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - resampy==0.2.2
    - rsa==4.7.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - seaborn==0.11.2
    - send2trash==1.8.0
    - sentencepiece==0.1.96
    - six==1.14.0
    - sklearn==0.0
    - sounddevice==0.4.3
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==2.0
    - tensorflow==2.6.0
    - tensorflow-addons==0.14.0
    - tensorflow-estimator==2.6.0
    - tensorflow-gpu==2.6.0
    - termcolor==1.1.0
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - torch==1.10.0+cu113
    - torch-complex==0.4.3
    - torch-optimizer==0.3.0
    - torchaudio==0.10.0+cu113
    - torchfile==0.1.0
    - torchvision==0.11.1+cu113
    - torchviz==0.0.2
    - tornado==6.1
    - tqdm==4.46.0
    - traitlets==5.1.1
    - typeguard==2.13.0
    - typing-extensions==3.7.4.3
    - umap-learn==0.5.2
    - unidecode==1.3.2
    - urllib3==1.26.7
    - vector-quantize-pytorch==0.10.15
    - visdom==0.1.8.9
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - webrtcvad==2.0.10
    - websocket-client==1.2.1
    - werkzeug==2.0.2
    - widgetsnbextension==3.5.2
    - wrapt==1.12.1
    - yacs==0.1.7
    - zipp==3.13.0
prefix: /home/grads/q/quamer.waris/anaconda3/envs/transformerv2
